const fs=require('fs'),path=require('path'),XLSX=require('xlsx'),AdmZip=require('adm-zip');
const OUT=path.join(process.cwd(),'..','data','mjr-recalls.json');
const URL={
 FDA:'https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts/datatables-data?_format=xlsx&page=',
 CPSC:'https://www.saferproducts.gov/RestWebServices/Recall?format=json',
 USDA:'https://www.fsis.usda.gov/fsis/api/recall/v/1',
 NHTSA:'https://static.nhtsa.gov/odi/ffdd/rcl/RCL_FROM_2025_2026.zip'
};
const PAGE={FDA:'https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts',CPSC:'https://www.cpsc.gov/Recalls',USDA:'https://www.fsis.usda.gov/recalls',NHTSA:'https://www.nhtsa.gov/recalls'};
const BRANDS=['great value','walmart','mainstays','costco','kirkland','target','aldi','kroger','publix','trader joe','whole foods','safeway','albertsons','meijer','nestle','kraft','heinz','general mills','kellogg','tyson','perdue','purina','pedigree','iams','royal canin','blue buffalo','fromm','northwest naturals','freshpet','abbott','baxter','b. braun','medtronic','ge healthcare','boston scientific','cuisinart','conair','apple','samsung','lg','whirlpool','ford','lincoln','chevrolet','gmc','buick','cadillac','toyota','lexus','honda','acura','nissan','infiniti','hyundai','kia','subaru','mazda','volkswagen','audi','bmw','mercedes','volvo','tesla','rivian','chrysler','dodge','jeep','ram'];
const clean=v=>String(v??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const low=v=>clean(v).toLowerCase();
const slug=v=>low(v).replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70);
function date(v){const s=clean(v);if(!s)return'';let m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return`${m[3]}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;if(/^\d{8}$/.test(s))return`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`;const d=new Date(s);return isNaN(d)?'':d.toISOString().slice(0,10)}
function age(d){if(!d)return999;return Math.max(0,Math.floor((Date.now()-new Date(d+'T12:00:00Z'))/86400000))}
const short=(v,n)=>{const s=clean(v);return s.length<=n?s:s.slice(0,n-1).replace(/\s+\S*$/,'')+'…'};
const major=v=>BRANDS.some(b=>low(v).includes(b));
const pet=v=>/pet food|dog food|cat food|dog treat|cat treat|feline|canine|milk replacer/i.test(v);
function category(v,type,source){const s=low(v+' '+type);if(source==='CPSC'||source==='NHTSA')return'consumer';if(/dietary supplement|drug|medical device|pharmaceutical|injection|tablet|capsule|syringe|catheter|implant|infusion/.test(s))return'health';if(pet(s)||/food|beverage|meat|poultry|egg|cheese|seafood|allergen|salmonella|listeria|e\. coli|stec/.test(s))return'food';return'consumer'}
function score(i){const s=low([i.title,i.reason,i.brand,i.company].join(' '));let n=age(i.date)<=1?75:age(i.date)<=3?60:age(i.date)<=7?45:age(i.date)<=14?20:0;if(/death|fatal|life-threatening|do not drive/.test(s))n+=65;if(/serious injury|class i|fire hazard|electrocution|explosion|crash risk/.test(s))n+=50;if(/salmonella|listeria|e\. coli|stec|botulism/.test(s))n+=42;if(/undeclared milk|undeclared peanut|undeclared egg|undeclared allergen|choking|suffocation|lead exposure/.test(s))n+=30;if(/particulate|foreign material|foreign object|contamination/.test(s))n+=15;if(i.units>=1000000)n+=80;else if(i.units>=500000)n+=70;else if(i.units>=100000)n+=52;else if(i.units>=25000)n+=34;if(i.majorBrand)n+=45;if(i.pet)n+=14;if(i.source==='NHTSA'&&i.units>=100000)n+=20;return n}
function units(v){const m=clean(v).match(/(?:about|approximately|nearly|more than|over)?\s*([\d,]+)\s+(?:units|vehicles|cars|trucks|products|items|devices|dressers|brushes|packages|cases|pounds)\b/i);return m?Number(m[1].replace(/,/g,''))||0:0}
async function buf(u){const r=await fetch(u,{headers:{'User-Agent':'MediaJobsReport-RecallFeed/1.0'}});if(!r.ok)throw Error(`${u} HTTP ${r.status}`);return Buffer.from(await r.arrayBuffer())}
async function json(u){const r=await fetch(u,{headers:{'User-Agent':'MediaJobsReport-RecallFeed/1.0','Accept':'application/json'}});if(!r.ok)throw Error(`${u} HTTP ${r.status}`);return r.json()}
function fdaTitle(b,p,c){const s=low(`${b} ${p} ${c}`);if(/northwest naturals/.test(s)&&/chicken/.test(s))return'Northwest Naturals Chicken Recipe Pet Food Recalled';if(/b\.?\s*braun/.test(s)&&/sodium chloride/.test(s))return'B. Braun Sodium Chloride Injection Recalled';if(/baxter/.test(s)&&/sodium chloride/.test(s))return'Baxter Sodium Chloride Injection Recalled';if(/feline milk replacer/.test(s))return'Shelter’s Choice and Breeder’s Edge Feline Milk Replacers Recalled';const product=short(clean(p).replace(/\bnet (?:wt|weight)\b.*$/i,'').replace(/\bupc\b.*$/i,''),75);return short(`${clean(b)?clean(b)+' ':''}${product||'Product'} Recalled`,100)}
async function FDA(){const wb=XLSX.read(await buf(URL.FDA),{type:'buffer'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});return rows.map(r=>{const d=date(r.Date),b=clean(r['Brand Name(s)']),p=clean(r['Product Description']),t=clean(r['Product Type']),reason=clean(r['Recall Reason Description']),company=clean(r['Company Name']),all=[b,p,t,reason,company].join(' ');const i={id:`FDA-${d}-${slug(b+'-'+p)}`,source:'FDA',category:category(all,t,'FDA'),title:fdaTitle(b,p,company),reason:short(reason,220),brand:b,company,product:p,date:d,units:0,pet:pet(all),majorBrand:major(all),url:PAGE.FDA};i.score=score(i);return i})}
async function CPSC(){const rows=await json(URL.CPSC);return (Array.isArray(rows)?rows:[]).map(r=>{const ps=(r.Products||[]).map(x=>clean(x.Name)).filter(Boolean),ms=(r.Manufacturers||[]).map(x=>clean(x.Name)).filter(Boolean),hs=(r.Hazards||[]).map(x=>clean(x.Name)).filter(Boolean),title=clean(r.Title||r.RecallTitle||ps[0]||'Consumer Product Recall'),reason=hs.join('; ')||clean(r.Description)||'Consumer product safety recall.',d=date(r.RecallDate||r.LastPublishDate),all=[title,reason,ms.join(' '),ps.join(' ')].join(' ');const i={id:`CPSC-${clean(r.RecallID||'')}-${slug(title)}`,source:'CPSC',category:'consumer',title:short(title,105),reason:short(reason,220),brand:ms[0]||'',company:ms.join(', '),product:ps.join(', '),date:d,units:units(all),pet:false,majorBrand:major(all),url:clean(r.URL||r.RecallURL)||PAGE.CPSC};i.score=score(i);return i})}
async function USDA(){const d=await json(URL.USDA),rows=Array.isArray(d)?d:(Array.isArray(d?.data)?d.data:[]);return rows.map(r=>{const title=clean(r.title||r.recall_title||r.field_title||'USDA Food Recall'),reason=clean(r.reason||r.summary||r.field_recall_reason||'USDA food safety recall.'),dt=date(r.date||r.recall_date||r.field_recall_date),company=clean(r.company||r.establishment||r.field_establishment),all=`${title} ${reason} ${company}`;const i={id:`USDA-${dt}-${slug(title)}`,source:'USDA',category:'food',title:short(title,105),reason:short(reason,220),brand:'',company,product:'',date:dt,units:units(all),pet:false,majorBrand:major(all),url:clean(r.url)||PAGE.USDA};i.score=score(i);return i})}
const NF=['RECORD_ID','CAMPNO','MAKETXT','MODELTXT','YEARTXT','MFGCAMPNO','COMPNAME','MFGNAME','BGMAN','ENDMAN','RCLTYPECD','POTAFF','ODATE','INFLUENCED_BY','MFGTXT','RCDATE','DATEA','RPNO','FMVSS','DESC_DEFECT','CONEQUENCE_DEFECT','CORRECTIVE_ACTION','NOTES','RCL_CMPT_ID','MFR_COMP_NAME','MFR_COMP_DESC','MFR_COMP_PTNO'];
async function NHTSA(){const z=new AdmZip(await buf(URL.NHTSA)),e=z.getEntries().find(x=>/\.txt$/i.test(x.entryName));if(!e)throw Error('No NHTSA TXT');const groups={};for(const line of e.getData().toString('utf8').split(/\r?\n/).filter(Boolean)){const v=line.split('\t'),r={};NF.forEach((f,i)=>r[f]=clean(v[i]||''));if(!r.CAMPNO)continue;const d=date(r.RCDATE);if(d&&age(d)>45)continue;groups[r.CAMPNO]??={campaign:r.CAMPNO,date:d,make:r.MAKETXT,manufacturer:r.MFGNAME,models:[],component:r.COMPNAME,defect:r.DESC_DEFECT,consequence:r.CONEQUENCE_DEFECT,units:Number(r.POTAFF)||0};const g=groups[r.CAMPNO];if(r.MODELTXT&&!g.models.includes(r.MODELTXT))g.models.push(r.MODELTXT);g.units=Math.max(g.units,Number(r.POTAFF)||0)}return Object.values(groups).map(g=>{const make=clean(g.make||g.manufacturer),title=make?(g.models.length===1?`${make} ${g.models[0]} Vehicles Recalled`:`${make} Vehicles Recalled`):'Vehicle Recall';let reason=clean(g.defect||g.consequence||g.component);if(g.units)reason+=` ${g.units.toLocaleString('en-US')} vehicles or units may be affected.`;const all=`${title} ${reason} ${g.manufacturer}`;const i={id:`NHTSA-${g.campaign}`,source:'NHTSA',category:'consumer',title:short(title,105),reason:short(reason,220),brand:make,company:clean(g.manufacturer),product:g.models.slice(0,6).join(', '),date:g.date,units:g.units,pet:false,majorBrand:major(all),campaign:g.campaign,url:PAGE.NHTSA};i.score=score(i);return i})}
function dedupe(a){const m=new Map;for(const i of a){const k=i.source==='NHTSA'?`NHTSA|${i.campaign}`:`${i.source}|${slug(i.title)}|${i.date}`;if(!m.has(k)||i.score>m.get(k).score)m.set(k,i)}return[...m.values()]}
(async()=>{console.log('Building MJR recall feed...');const rs=await Promise.allSettled([FDA(),CPSC(),USDA(),NHTSA()]),names=['FDA','CPSC','USDA','NHTSA'],sources={};let all=[];rs.forEach((r,n)=>{const name=names[n];if(r.status==='fulfilled'){sources[name]={ok:true,count:r.value.length};all=all.concat(r.value);console.log(name,r.value.length)}else{sources[name]={ok:false,count:0,error:String(r.reason?.message||r.reason)};console.warn(name,'FAILED',r.reason)}});all=dedupe(all).filter(i=>i.date&&age(i.date)<=45).sort((a,b)=>(b.score-a.score)||b.date.localeCompare(a.date)).slice(0,120);const newestDate=all.reduce((x,i)=>i.date>x?i.date:x,'');const out={generated:new Date().toISOString(),newestDate,stale:newestDate?age(newestDate)>7:true,sources,count:all.length,items:all};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(out,null,2)+'\n');console.log('Newest:',newestDate,'Total:',all.length);all.slice(0,15).forEach((i,n)=>console.log(`${n+1}. [${i.source}] ${i.date} | ${i.score} | ${i.title}`))})().catch(e=>{console.error(e);process.exit(1)});
